# Generated by Django 5.0 on 2023-12-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardModel',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='SubjectModel',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='TopicModel',
            new_name='Topic',
        ),
    ]
