# Generated by Django 5.0 on 2023-12-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_rename_cardmodel_card_rename_subjectmodel_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='flash_cards',
        ),
        migrations.AddField(
            model_name='card',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.subject'),
        ),
    ]
