# Generated by Django 5.0 on 2023-12-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_alter_quiz_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizflashcard',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quizflashcard',
            name='question',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='flashcards',
            field=models.ManyToManyField(blank=True, null=True, through='flashcard.QuizFlashCard', to='flashcard.card'),
        ),
        migrations.AlterField(
            model_name='quizflashcard',
            name='flashcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.card'),
        ),
        migrations.AlterField(
            model_name='quizflashcard',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.quiz'),
        ),
    ]
