# Generated by Django 5.0 on 2023-12-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_remove_quizflashcard_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='flashcards',
            field=models.ManyToManyField(blank=True, through='flashcard.QuizFlashCard', to='flashcard.card'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topics',
            field=models.ManyToManyField(blank=True, to='flashcard.topic'),
        ),
    ]
