# Generated by Django 5.0 on 2023-12-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_alter_quiz_flashcards_alter_quiz_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='flashcards',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topics',
        ),
        migrations.AddField(
            model_name='card',
            name='flash_quiz',
            field=models.ManyToManyField(blank=True, to='flashcard.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.topic'),
        ),
        migrations.DeleteModel(
            name='QuizFlashCard',
        ),
    ]
