# Generated by Django 5.0 on 2023-12-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0013_review_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.card')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.card')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.question')),
            ],
        ),
    ]
