# Generated by Django 5.0 on 2023-12-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0014_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='card',
        ),
        migrations.RemoveField(
            model_name='question',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='choice',
            field=models.ManyToManyField(blank=True, to='flashcard.choice'),
        ),
        migrations.AddField(
            model_name='card',
            name='question',
            field=models.ManyToManyField(blank=True, to='flashcard.question'),
        ),
    ]
