# Generated by Django 5.0 on 2023-12-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0016_remove_card_choice_remove_card_question_choice_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='review_cards',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
