# Generated by Django 5.0 on 2024-01-04 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0019_alter_card_flash_quiz_alter_card_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flash_quiz',
            field=models.ManyToManyField(blank=True, to='flashcard.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard.topic'),
        ),
    ]
