# Generated by Django 5.0 on 2024-01-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0020_alter_card_flash_quiz_alter_quiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flash_quiz',
            field=models.ManyToManyField(to='flashcard.quiz'),
        ),
    ]
