# Generated by Django 5.0 on 2024-01-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0023_alter_card_flash_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flash_quiz',
            field=models.ManyToManyField(blank=True, to='flashcard.quiz'),
        ),
    ]
